owner: makcdot
repo: korvus-status

sites:
  - name: 🌐 Сайт Корвус
    url: https://korvusbot.com
  - name: 🗄️ База Даних (Mongoose)
    url: https://korvusbot.com/api/health/database
    expectedStatusCodes: [200]

status-website:
  cname: status.korvusbot.com
  name: Статус Корвус
  introTitle: "**Корвус** моніторинг сервісів"
  introMessage: Тут ви можете перевірити стабільність роботи бота, вебсайту та бази даних.
  logoUrl: https://cdn.discordapp.com/avatars/1380916694863581284/твій_аватар.png
  theme: dark

i18n:
  activeIncidents: Активні інциденти
  allSystemsOperational: Усі системи працюють стабільно
  incidentReport: "Звіт про інцидент #$NUMBER"
  activeIncidentSummary: Відкрито $DATE, оновлено $UPDATES
  incidentTitle: Деталі інциденту $DATE
  publishedAt: Опубліковано о $DATE
