owner: Makc228
repo: korvus-status

sites:
  - name: Корвус
    url: https://korvusbot.com
  - name: База Даних
    url: https://korvusbot.com/api/health/database
    expectedStatusCodes: [200]

status-website:
  cname: status.korvusbot.com
  name: Статус Корвус
  introTitle: "**Корвус** моніторинг сервісів"
  introMessage: Тут ви можете перевірити стабільність роботи бота, вебсайту та бази даних.
  logoUrl: https://i.postimg.cc/h45djwy5/a-3a612fb0350c60fe96a7c65cb528e629.gif
  theme: dark

i18n:
  activeIncidents: Активні інциденти
  allSystemsOperational: Усі системи працюють стабільно
  incidentReport: "Звіт про інцидент #$NUMBER"
  activeIncidentSummary: Відкрито $DATE, оновлено $UPDATES
  incidentTitle: Деталі інциденту $DATE
  publishedAt: Опубліковано о $DATE
